apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Chart.AppVersion }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.global.ports.exchangeGeneratorService }}
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/app/config/application.yaml
        - name: LOGGING_CONFIG
          value: file:/app/resources/logback-spring.xml
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: config-volume
          mountPath: /app/resources
          subPath: logback-spring.xml
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config
          items:
          - key: application.yaml
            path: application.yaml
          - key: logback-spring.xml
            path: logback-spring.xml
