server:
  port: {{ .Values.global.ports.notificationsService}}

spring:
  application:
    name: {{ .Chart.name}}

    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {{ .Values.global.keycloak.issuerUrl | quote }}
  kafka:
    bootstrap-servers: {{ .Values.global.kafka.bootstrapServers | default "kafka.kafka.svc.cluster.local:9092" }}

kafka:
  topic: {{ .Values.kafka.topic }}
  group: {{ .Values.kafka.group }}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.bank.notifications: INFO
