server:
  port: {{ .Values.global.ports.notificationsService}}

spring:
  application:
    name: {{ .Chart.name}}

    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {{ .Values.global.keycloak.issuerUrl | quote }}
  kafka:
    bootstrap-servers: {{ .Values.global.kafka.bootstrapServers | default "kafka.kafka.svc.cluster.local:9092" }}
  zipkin:
    base-url: http://zipkin.{{ .Values.global.monitoring.namespace | default "monitoring" }}:9411
    enabled: true
  sleuth:
    sampler:
      probability: {{ .Values.global.tracing.samplingRate | default 1.0 }}
kafka:
  topic: {{ .Values.kafka.topic }}
  group: {{ .Values.kafka.group }}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: {{ .Chart.Name }}
      environment: {{ .Values.global.environment | default "dev" }}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    com.bank.notifications: INFO
