replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.10.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5601
  name: kibana

# Конфигурация подключения к Elasticsearch
config:
  elasticsearch.hosts: ["http://elasticsearch:9200"]
  server.name: kibana
  server.host: "0.0.0.0"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"