server:
  port: 8085

spring:
  application:
    name: transfer
#  config:
#    import: "optional:consul:"
#
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        enabled: true
#        health-check-path: /actuator/health
#        service-name: transfer-service
  security:
    oauth2:
      client:
        provider:
          my-provider-keycloak:
            issuer-uri: ${ISSUER_URL:http://localhost:8180/realms/bank}
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: my-provider-keycloak
            client-id: api-gateway
            client-secret: t0GNfKIjwDNOZdeMyP9nX2gjc7EA7c7e
            redirect-uri: ${APP_BASE_URL:http://localhost:8090}/login/oauth2/code/{registrationId}
            scope: openid, profile, email
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URL:http://keycloak:8080/realms/bank/protocol/openid-connect/certs}

clients:
  user-client:
    base-url: ${USER_CLIENT_BASE_URL:http://localhost:8090/api/accounts}
  blocker-client:
    base-url: ${BLOCKER_CLIENT_BASE_URL:http://localhost:8090/api/blocker}
  notification-client:
    base-url: ${NOTIFICATION_CLIENT_BASE_URL:http://localhost:8090/api/notification}
  exchange-client:
    base-url: ${EXCHANGE_CLIENT_BASE_URL:http://localhost:8090/api/exchange}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.consul: DEBUG
    com.bank.transfer: DEBUG
