server:
  port: {{ .Values.global.ports.exchangeService}}

spring:
  application:
    name: {{ .Chart.Name }}
  kafka:
    bootstrap-servers: {{ .Values.global.kafka.bootstrapServers | default "kafka.kafka.svc.cluster.local:9092" }}
  zipkin:
    base-url: http://zipkin.{{ .Values.global.monitoring.namespace | default "monitoring" }}:9411
    enabled: true
  sleuth:
    sampler:
      probability: {{ .Values.global.tracing.samplingRate | default 1.0 }}
kafka:
  topic: {{ .Values.kafka.topic }}
  group: {{ .Values.kafka.group }}
  datasource:
    url: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
    username:  {{ .Values.database.username | quote }}
    password:  {{ .Values.database.password | quote }}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          my-provider-keycloak:
            issuer-uri: {{ .Values.global.keycloak.issuerUrl | quote }}
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: my-provider-keycloak
            client-id: api-gateway
            client-secret: t0GNfKIjwDNOZdeMyP9nX2gjc7EA7c7e
            redirect-uri: ${APP_BASE_URL:http://localhost:8090}/login/oauth2/code/{registrationId}
            scope: openid, profile, email
      resourceserver:
        jwt:
          jwk-set-uri: {{ .Values.global.keycloak.jwtSetUrl | quote }}
clients:
  notification-client:
    base-url: {{ .Values.global.baseUrl.notificationService | quote }}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: {{ .Chart.Name }}
      environment: {{ .Values.global.environment | default "dev" }}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.security: INFO
    com.bank.accounts: INFO
