spring:
  application:
    name: api-gateway
  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        service-name: api-gateway

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: root-route
          uri: no://op
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /login

        - id: front-ui-route
          uri: lb://front-ui #  http://host.docker.internal:8081
          order: 10000
          predicates:
            - Path=/**
          filters:
            - TokenRelay

        - id: accounts-service
          uri: lb://accounts
          predicates:
            - Path=/api/accounts/**
          filters:
            - TokenRelay

        - id: exchange-service
          uri: lb://exchange
          predicates:
            - Path=/api/exchange/**
          filters:
            - TokenRelay

        - id: blocker-service
          uri: lb://blocker
          predicates:
            - Path=/api/blocker/**
          filters:
            - TokenRelay

        - id: notifications-service
          uri: lb://exchange
          predicates:
            - Path=/api/notification/**
          filters:
            - TokenRelay

        - id: cash-service
          uri: lb://cash
          predicates:
            - Path=/api/cash/**
          filters:
            - TokenRelay

server:
  port: 8090
  reactive:
    session:
      cookie:
        name: SESSION_${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.consul: INFO