server:
  port: 8082

spring:
  application:
    name: accounts
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092

#  config:
#    import: "optional:consul:"
#
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        enabled: true
#        health-check-path: /actuator/health
#        service-name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: root
    password: 19931012
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          my-provider-keycloak:
            issuer-uri: ${ISSUER_URL:http://localhost:8180/realms/bank}
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: my-provider-keycloak
            client-id: api-gateway
            client-secret: t0GNfKIjwDNOZdeMyP9nX2gjc7EA7c7e
            redirect-uri: ${APP_BASE_URL:http://localhost:8090}/login/oauth2/code/{registrationId}
            scope: openid, profile, email
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URL:http://localhost:8180/realms/bank/protocol/openid-connect/certs}
clients:
  notification-client:
    base-url: ${NOTIFICATION_CLIENT_BASE_URL:http://localhost:8090/api/notification}

logging:
  level:
    org.springframework.security: DEBUG
    com.bank.accounts: DEBUG