apiVersion: v2
name: bank-app
description: Bank Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ingress
    version: "0.1.0"
    repository: "file://charts/ingress"
  - name: keycloak
    version: "0.1.0"
    repository: "file://charts/keycloak"
  - name: postgresql
    version: "0.1.0"
    repository: "file://charts/postgresql"
  - name: account-service
    version: "0.1.0"
    repository: "file://charts/account-service"
  - name: blocker-service
    version: "0.1.0"
    repository: "file://charts/blocker-service"
  - name: cash-service
    version: "0.1.0"
    repository: "file://charts/cash-service"
  - name: exchange-generator-service
    version: "0.1.0"
    repository: "file://charts/exchange-generator-service"
  - name: exchange-service
    version: "0.1.0"
    repository: "file://charts/exchange-service"
  - name: front-ui-service
    version: "0.1.0"
    repository: "file://charts/front-ui-service"
  - name: notifications-service
    version: "0.1.0"
    repository: "file://charts/notifications-service"
  - name: transfer-service
    version: "0.1.0"
    repository: "file://charts/transfer-service"
