apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
  namespace: {{ .Values.global.namespace }}
data:
  init-databases.sql: |
{{ .Files.Get "files/init-databases.sql" | indent 4 }}
