apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-realm
  namespace: {{ .Values.global.namespace }}
data:
  realm-export.json: |
{{ .Files.Get "files/realm-export.json" | indent 4 }}

