apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
    chart: logstash-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9600
              name: http
          env:
            - name: XPACK_MONITORING_ENABLED
              value: "false"
            - name: PIPELINE_WORKERS
              value: "{{ .Values.config.pipeline.workers }}"
            - name: PIPELINE_BATCH_SIZE
              value: "{{ .Values.config.pipeline.batch.size }}"
            - name: PIPELINE_BATCH_DELAY
              value: "{{ .Values.config.pipeline.batch.delay }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pipeline-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
          livenessProbe:
            exec:
              command: ["curl", "-f", "http://localhost:9600/"]
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["curl", "-f", "http://localhost:9600/"]
            initialDelaySeconds: 30
            periodSeconds: 5
      volumes:
        - name: pipeline-config
          configMap:
            name: logstash-pipeline
        - name: config
          configMap:
            name: logstash-config