server:
  port: 8088

spring:
  application:
    name: notifications
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092

#  config:
#    import: "optional:consul:"
#
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        enabled: true
#        health-check-path: /actuator/health
#        service-name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8180/realms/bank}
kafka:
  topic: notifications
  group: notifications-group

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.bank.notifications: INFO
