apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    # Аннотации для Prometheus
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/scheme: "http"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.global.ports.exchangeService }}
    targetPort: {{ .Values.global.ports.exchangeService }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
